### ISSUE TITLE
Опечатка у методі ftello(file_to_hide). Має бути ftell(file_to_hide) скоріш за все. 

### ISSUE THREAD

**Issue by olesuv** [konorth3/steganography#1]
https://github.com/konorth3/steganography/blob/34d0b864b95204adf47db47e54b8cd88fea8beec/steg.c#L311

**Comment by konorth3** [comment]
ftello і ftell одинаково працюють для обмежень цього коду (загальна характеристика всього коду вже описана на рядку 300 *кхе-кхе*)

**Comment by olesuv** [comment]
Зрозумів. Програма не запускалась на моєму компʼютері, писало помилка в тому рядку, тому змінив на `ftell` і після компіляції запрацювала.

**Comment by konorth3** [comment]
Якщо це реальна проблема, то до відкритої баги варто добавляти опис з кроками як її вдалося відтворити. Ця проблема може виникати якщо ти використовуєш застарілі бібліотеки https://linux.die.net/man/3/ftello
